//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DBContextLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendenceId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> NumberOfDays { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
