//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DBContextLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRide
    {
        public int CustomerRideId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> TaxiDriverId { get; set; }
        public string PickupLocation { get; set; }
        public string DropLocation { get; set; }
        public int RideStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual TaxiDriver TaxiDriver { get; set; }
    }
}
