//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DBContextLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Gender { get; set; }
        public string ContactNo { get; set; }
        public string CustomerPassword { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
    
        public virtual Gender Gender1 { get; set; }
    }
}
