//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DBContextLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxiMasterEntities : DbContext
    {
        public TaxiMasterEntities()
            : base("name=TaxiMasterEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Taxi> Taxi { get; set; }
        public virtual DbSet<TaxiDriver> TaxiDriver { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Salary> Salary { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<CustomerRide> CustomerRide { get; set; }
    }
}
